version: '3.5'

services:

  #nome do servico
  webscraping-python:

    #construido a partir de uma imagem customizada em ./image
    image: webscraping-python
    
    #nome do conteiner
    container_name: webscraping-python

    #pastas compartilhadas
    volumes:
      #pasta do codigo fonte da aplicacao
      - "./app:/root"
  
    #artifício para manter o container aberto
    tty: true
